[package]
name = "chem-eq"
version = "0.1.0"
edition = "2021"
description = "Parse chemical equations and balance, get mol ratios, or elide states on them"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = { version = "0.31.3", optional = true }
nom = "7.1.1"

[features]
default = ["balance"]
balance = ["dep:nalgebra"]
