name: Format
on: [push, pull_request]

defaults:
  run:
    working-directory: src-tauri

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          components: rustfmt
          rust-version: nightly
      - uses: actions/checkout@main
      - name: Check format
        run: cargo fmt --all -- --check
