name: rust-format
on: [push, pull_request, workflow_dispatch]

defaults:
  run:
    working-directory: src-tauri

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: actions/checkout@v3
      - name: Check format
        run: cargo fmt --all -- --check
