name: vitest

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Get node
        uses: actions/setup-node@v3
        with:
          node-version: 19.0
          cache: 'npm'
      - name: Execute Unit tests
        run: |
          yarn install --frozen-lockfile
          yarn test:unit
